const products = [
  {
    name: 'AirPods',
    price: 35,
    image: '/products/airpods.jpg',
    variants: ['AirPods Gen 1', 'AirPods Gen 2', 'AirPods Pro', 'AirPods Pro 2'],
    outOfStock: false,
  },
  {
    name: 'AirPods Max',
    price: 110,
    image: '/products/airpodsmax.jpg',
    variants: ['Silver', 'Space Gray', 'Sky Blue', 'Green', 'Pink'],
    outOfStock: false,
  },
  {
    name: 'Colognes',
    price: 50,
    image: '/products/colognes.jpg',
    variants: [
      'Bleu de Chanel',
      'Aventus Creed',
      'Versace Eros',
      'Versace Bright Crystal',
      'Chanel N°5',
      'Valentino Uomo Born in Roma (Sold Out)',
      'YSL Libre',
      'Y Eau de Parfum (Sold Out)',
      'Jean Paul Gaultier (Sold Out)',
      'Percival Eau de Parfum (Sold Out)',
      'Sauvage Dior (Sold Out)',
      'Sauvage Dior Elixir (Sold Out)',
      'Tom Ford Lost Cherry (Sold Out)',
      'Tom Ford Oud Wood (Sold Out)',
      'Tom Ford Tobacco Vanille (Sold Out)',
      'Baccarat Rouge 540 (Sold Out)',
    ],
    outOfStock: false,
  },
  {
    name: 'Denim Tears Hoodie',
    price: 85,
    image: '/products/denimtears.jpg',
    variants: ['All Colors / Sizes'],
    outOfStock: true,
  },
  {
    name: 'Sp5der Hoodie',
    price: 85,
    image: '/products/sp5der.jpg',
    variants: [
      'Pink Web Hoodie',
      'Black Web Hoodie',
      'Blue Star Hoodie',
      'Green Star Hoodie',
      'Red Web Hoodie',
    ],
    outOfStock: false,
  },
  {
    name: 'Rolex Watch',
    price: 150,
    image: '/products/rolex.jpg',
    variants: [
      'Daytona (No Box)',
      'GMT-Master II (No Box)',
      'Datejust (No Box)',
      'Day-Date (No Box)',
      'Arabic Dial (No Box)',
      'Day-Date Oyster Perpetual (No Box)',
      'Explorer (No Box)',
      'Yacht-Master (No Box)',
      'Sky-Dweller (No Box)',
    ],
    outOfStock: false,
  },
  {
    name: 'iPhone 15 Pro Max',
    price: 500,
    image: '/products/iphone.jpg',
    variants: ['Highest Quality – iOS System'],
    outOfStock: false,
  },
  {
    name: 'Moissanite Bracelet',
    price: 250,
    image: '/products/moissanite-bracelet.jpg',
    variants: ['Standard'],
    outOfStock: false,
  },
  {
    name: 'Moissanite Stud Earrings',
    price: 50,
    image: '/products/moissanite-earrings.jpg',
    variants: ['Standard'],
    outOfStock: false,
  },
  {
    name: 'JBL Flip 5',
    price: 45,
    image: '/products/jbl-flip5.jpg',
    variants: ['Standard'],
    outOfStock: false,
  },
  {
    name: 'JBL Clip 4',
    price: 45,
    image: '/products/jbl-clip4.jpg',
    variants: ['Standard'],
    outOfStock: false,
  },
  {
    name: 'Apple Watch Series 9',
    price: 150,
    image: '/products/applewatch9.jpg',
    variants: ['Highest Quality'],
    outOfStock: false,
  },
  {
    name: 'Apple Watch Ultra 2',
    price: 150,
    image: '/products/applewatch-ultra.jpg',
    variants: ['Highest Quality'],
    outOfStock: false,
  },
  {
    name: 'Dyson Hair Dryer',
    price: 120,
    image: '/products/dyson-hairdryer.jpg',
    variants: ['Standard'],
    outOfStock: true,
  },
  {
    name: 'Dyson Airwrap Complete Set',
    price: 200,
    image: '/products/dyson-airwrap.jpg',
    variants: ['Complete Set'],
    outOfStock: true,
  },
]

export default products
